FROM nginx:1.18-alpine

ENV TZ=Asia/Tokyo

# nginx config file
COPY ./docker/nginx/default-prod.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/ssl/ssl_certificate_appName.crt /etc/ssl/ssl_certificate_appName.crt
COPY ./docker/nginx/ssl/ssl_certificate_appName.key /etc/ssl/ssl_certificate_appName.key

WORKDIR /var/www/html
